version: '3.2'

services:

  app:
    container_name: ${CONTAINER_PREFIX}_app
    build: docker/php
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  mysql:
    container_name: ${CONTAINER_PREFIX}_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
